apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/wkol/zprp-diet-assistant/backend:latest
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: 5432
            - name: POSTGRES_DB
              value: backend
            - name: POSTGRES_USER
              value: backend
            - name: POSTGRES_PASSWORD
              value: backend
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.local
            - name: DJANGO_SECRET_KEY
              value: KXsmvYqwQgrUjhfASPhgaBBaxCaXfswYBfuCfeIrbdnkbPxlrG
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"