apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/k-litman/zprp-diet-assistant/backend:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "250Mi"
              cpu: "125m"
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: backend
            - name: POSTGRES_USER
              value: backend
            - name: POSTGRES_PASSWORD
              value: backend
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings.production"
            - name: DJANGO_SECRET_KEY
              value: "KXsmvYqwQgrUjhfASPhgaBBaxCaXfswYBfuCfeIrbdnkbPxlrG"
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379"
      restartPolicy: Always