apiVersion: apps/v1
kind: Deployment
metadata:
  name: celeryworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celeryworker
  template:
    metadata:
      labels:
        app: celeryworker
    spec:
      containers:
        - name: celeryworker
          image: ghcr.io/k-litman/zprp-diet-assistant/backend:sha-371e47e
          command:
            - /start-celeryworker.sh
          ports:
            - containerPort: 5672
          resources:
            requests:
              memory: "250Mi"
              cpu: "125m"
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: backend
            - name: POSTGRES_USER
              value: backend
            - name: POSTGRES_PASSWORD
              value: backend
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings.production"
            - name: DJANGO_SECRET_KEY
              value: "KXsmvYqwQgrUjhfASPhgaBBaxCaXfswYBfuCfeIrbdnkbPxlrG"
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379"
            - name: CORS_ORIGIN_WHITELIST
              value: "http://localhost:5173,https://zprp.fridaydeployment.com,http://zprp.fridaydeployment.com"
            - name: CSRF_TRUSTED_ORIGINS
              value: "localhost:5173,zprp.fridaydeployment.com"
            - name: SENTRY_DSN
              value: "https://91ca397292f4790a277259590c7101dd@o4506361867599872.ingest.sentry.io/4506546668765184"
      restartPolicy: Always