apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/k-litman/zprp-diet-assistant/frontend:sha-ade614c
          name: frontend
          env:
            - name: VITE_API_URL
              value: "https://api.zprp.fridaydeployment.com"
          ports:
            - containerPort: 4173