apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zprp-diet-assistant-ingress
spec:
  rules:
    - host: zprp.fridaydeployment.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000