# Generated by Django 4.1.13 on 2024-01-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet_plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meal",
            name="cuisine_type",
            field=models.CharField(
                choices=[
                    ("it", "Italian"),
                    ("pl", "Polish"),
                    ("fr", "French"),
                    ("mx", "Mexican"),
                    ("as", "Asian"),
                    ("sp", "Spanish"),
                    ("us", "American"),
                ],
                max_length=20,
            ),
        ),
    ]
