# Generated by Django 4.1.13 on 2024-01-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet_plans", "0002_dietplan_generated_alter_meal_cuisine_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietplan",
            name="generated",
        ),
        migrations.AddField(
            model_name="dietplan",
            name="error",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dietplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generated", "Generated"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
