# Generated by Django 4.1.13 on 2024-01-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet_plans", "0003_remove_dietplan_generated_dietplan_error_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietplan",
            old_name="error",
            new_name="error_message",
        ),
    ]
