name: Test backend
on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/test-backend.yml

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy env
        working-directory: backend
        run: |
          cp .env.template .env
      - name: Lint check
        working-directory: backend
        run: |
          ./manage.sh lint
      - name: Run tests
        working-directory: backend
        run: |
          ./manage.sh ci-test
      - name: Validate OpenAPI schema
        working-directory: backend
        run: |
          ./manage.sh validate-spec